k9s:
  ui:
    enableMouse: false
    headless: false
    logoless: true
    crumbsless: false
    skin: dracula
    defaultsToFullScreen: true
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: -1
  noExitOnCtrlC: true
  skipLatestRevCheck: true
